# Generated by Django 3.0.5 on 2020-05-11 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_wfe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="logfile",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name="job", name="uuid", field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
