# Generated by Django 3.0.5 on 2020-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_wfe", "0002_auto_20200511_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="current_step",
            field=models.CharField(
                default="django_wfe.steps.__start__", max_length=300
            ),
        ),
        migrations.DeleteModel(name="Step",),
    ]
